export const DEMO_DATA = {
  id:"root",title:"My Library",type:"directory",
  children:[{
    id:"demo",title:"Demo Deck",type:"topic",path:[],cards:[
      {id:"d-1",order:1,title:"What Critical Thinking Actually Is",body:"Critical thinking is the disciplined practice of evaluating information before accepting it. It means asking whether evidence supports a claim, who is making it, and what might be missing from the picture.",context:"Most people think they think critically — but critical thinking is a skill, not a personality trait. It requires deliberate effort and specific techniques, not just a skeptical attitude.",tags:["foundational"],difficulty:1},
      {id:"d-2",order:2,title:"Confirmation Bias",body:"The brain naturally seeks information that confirms what it already believes and dismisses what contradicts it. This happens automatically — you don't decide to do it.",context:"Confirmation bias is the most documented cognitive bias in psychology. It affects experts as much as novices. Awareness helps, but the only real counter is actively seeking disconfirming evidence.",tags:["bias","foundational"],difficulty:1},
      {id:"d-3",order:3,title:"The Difference Between Opinion and Argument",body:"An opinion is a position. An argument is a position supported by reasons and evidence. Saying 'I think X' is an opinion. Saying 'X is true because of Y and Z' is the beginning of an argument.",context:"Many debates stall because people treat disagreement as a clash of preferences rather than a question to be reasoned through. Upgrading from opinion to argument is the first step in productive disagreement.",tags:["foundational","communication"],difficulty:1},
      {id:"d-4",order:4,title:"Evidence vs. Anecdote",body:"Anecdotes are individual stories. Evidence is systematically collected data across many cases. One person's experience is real but not representative — it may be the exception, not the rule.",context:"'My grandfather smoked all his life and lived to 95' is an anecdote. It doesn't challenge the statistical evidence on smoking. Human memory is better at storing stories than patterns, which is why anecdotes feel so compelling.",tags:["evidence","mechanism"],difficulty:1},
      {id:"d-5",order:5,title:"Correlation vs. Causation",body:"Two things can move together without one causing the other. Ice cream sales and drowning rates both rise in summer — not because ice cream causes drowning, but because heat causes both.",context:"Establishing causation requires ruling out confounding variables, ideally through controlled experiments. Observational data shows correlation; randomised controlled trials are the gold standard for causation.",tags:["mechanism","evidence"],difficulty:2},
      {id:"d-6",order:6,title:"The Straw Man Fallacy",body:"A straw man misrepresents someone's argument to make it easier to attack. Instead of engaging with what they actually said, you argue against a weaker version of their position.",context:"Straw manning often happens unintentionally — we paraphrase badly or assume the worst version of an opponent's view. The test: would they recognise their position in your description of it?",tags:["fallacy","communication"],difficulty:2},
      {id:"d-7",order:7,title:"The Steel Man",body:"The steel man is the opposite of the straw man: engage with the strongest possible version of an opposing argument, not the weakest. If you can defeat the best version, your own position is much stronger.",context:"Steel manning is rare because it's uncomfortable — it requires genuinely understanding why intelligent people disagree with you. It's also the most effective form of intellectual preparation.",tags:["technique","communication"],difficulty:2},
      {id:"d-8",order:8,title:"Ad Hominem: Attacking the Person",body:"An ad hominem attacks the person making an argument rather than the argument itself. Even if the person is wrong about other things, unlikable, or biased — that doesn't make their specific claim false.",context:"Ad hominem is a fallacy because the truth of a claim is independent of who makes it. A corrupt politician can cite accurate statistics. Evaluate the argument, not the speaker.",tags:["fallacy"],difficulty:2},
      {id:"d-9",order:9,title:"Asking Better Questions",body:"The quality of your thinking is largely determined by the quality of your questions. 'Is this true?' is weaker than 'What would have to be true for this to be false?' — the second forces concrete thinking.",context:"Good questions expose hidden assumptions, clarify vague terms, and identify what evidence would actually settle a dispute. 'What do you mean by X?' is one of the most powerful questions in any discussion.",tags:["technique","foundational"],difficulty:2},
      {id:"d-10",order:10,title:"Intellectual Humility",body:"Intellectual humility is holding your beliefs proportionally to the evidence — and being genuinely willing to change your mind when evidence demands it. It is not the same as being uncertain about everything.",context:"Strong reasoners update beliefs incrementally as evidence accumulates. They distinguish between 'I haven't seen evidence for X' and 'X is false'. Overconfidence is a bigger epistemic risk than under-confidence for most people.",tags:["mindset","foundational"],difficulty:2},
      {id:"d-11",order:11,title:"The Socratic Method",body:"The Socratic method uses targeted questions to expose contradictions in a person's reasoning, helping them arrive at clearer thinking through dialogue rather than being told the answer.",context:"Socrates claimed to know nothing — but his questions dismantled the certainty of everyone he spoke to. The method works because people defend conclusions they reached themselves far more than conclusions handed to them.",tags:["technique","advanced"],difficulty:3},
      {id:"d-12",order:12,title:"Applying It Every Day",body:"Critical thinking isn't reserved for debates or essays. Every time you read a headline, receive advice, or form an opinion, you can ask: What's the evidence? Who benefits from me believing this? What am I not seeing?",context:"The goal isn't paralysis or perpetual scepticism — it's calibrated belief. You act on the best available evidence while staying open to revision. That combination is what separates good reasoning from both gullibility and cynicism.",tags:["application","foundational"],difficulty:1},
    ]
  },{
    id:"learn",title:"How to Learn Anything",type:"topic",path:[],cards:[
      {id:"l-1",order:1,title:"Why Most Studying Fails",body:"Rereading, highlighting, and passive review feel productive but produce little retention. The brain strengthens memories through retrieval, not exposure. Effort during recall is the signal for long-term storage.",context:"The 'fluency illusion' tricks you — familiar material feels learned because it's easy to read, not because it's encoded. Recognising a concept is far easier than recalling it from scratch.",tags:["foundational"],difficulty:1},
      {id:"l-2",order:2,title:"Active Recall",body:"Active recall means retrieving information from memory before looking it up. Closing your notes and answering questions from scratch is more effective than re-reading the same page three times.",context:"Each retrieval attempt strengthens the memory trace and identifies gaps. The harder the retrieval, the stronger the encoding — this is called the 'desirable difficulty' principle.",tags:["foundational","technique"],difficulty:1},
      {id:"l-3",order:3,title:"The Forgetting Curve",body:"Without review, you forget roughly 70% of new information within 24 hours. The curve is steep initially, then flattens. Each review resets it — and raises the floor slightly higher.",context:"Hermann Ebbinghaus mapped this in 1885 by memorising nonsense syllables. The curve shape is consistent across subjects and people, though the slope varies with meaningfulness of material.",tags:["mechanism"],difficulty:1},
      {id:"l-4",order:4,title:"Spaced Repetition",body:"Spacing reviews out over increasing intervals dramatically slows forgetting. Instead of cramming once, you review after 1 day, then 3 days, then a week, then a month.",context:"Spaced repetition exploits the forgetting curve deliberately — you review just before you would forget. Apps like Anki calculate these intervals automatically using the SM-2 algorithm.",tags:["technique","foundational"],difficulty:1},
      {id:"l-5",order:5,title:"Interleaving",body:"Mixing different topics or problem types in a single study session improves long-term retention, even though it feels harder and slower than blocking one topic at a time.",context:"Blocked practice builds fluency within a session. Interleaved practice builds discrimination — the ability to choose the right approach. This gap matters in real-world application.",tags:["technique"],difficulty:2},
      {id:"l-6",order:6,title:"The Feynman Technique",body:"To test real understanding, explain a concept as if teaching it to someone with no background. Where you stumble or use jargon is where your understanding has gaps.",context:"Named after physicist Richard Feynman, who credited his insight to his inability to understand something until he could explain it simply. 'If you can't explain it simply, you don't understand it well enough.'",tags:["technique","self-testing"],difficulty:1},
      {id:"l-7",order:7,title:"Chunking",body:"Chunking groups individual pieces of information into meaningful units. Experts see chess positions as patterns, not individual pieces — this is chunking in action.",context:"Working memory holds roughly 4 items at once. Chunking compresses information so a single 'slot' holds a rich concept. Mastery in any domain is largely the accumulation of useful chunks.",tags:["mechanism","foundational"],difficulty:2},
      {id:"l-8",order:8,title:"Elaborative Interrogation",body:"Asking 'why is this true?' and 'how does this connect to what I already know?' deepens encoding. Shallow processing stores isolated facts; deep processing builds connected knowledge.",context:"Elaboration forces you to construct meaning rather than copy it. The more connections a memory has to existing knowledge, the more retrieval paths exist — making it harder to forget.",tags:["technique"],difficulty:2},
      {id:"l-9",order:9,title:"The Illusion of Competence",body:"Familiarity masquerades as knowledge. If you can follow an explanation without confusion, you may feel you understand it — but following is passive, not generative.",context:"Testing yourself breaks the illusion. If you can't produce the explanation unprompted, you don't own the knowledge yet. This is why worked examples should always be followed by independent attempts.",tags:["pitfall","self-testing"],difficulty:2},
      {id:"l-10",order:10,title:"Metacognition",body:"Metacognition is thinking about your own thinking — monitoring whether you actually understand something versus just feeling like you do. Strong learners constantly audit their own comprehension.",context:"Poor metacognition is why students often study the wrong things before exams. Calibration — accurately sensing what you know and don't know — is a trainable skill, not a fixed trait.",tags:["foundational","self-testing"],difficulty:2},
      {id:"l-11",order:11,title:"Transfer: The Real Goal",body:"Transfer is applying knowledge in new contexts — the ultimate test of understanding. Most studying optimises for recognition on familiar problems, not transfer to novel ones.",context:"Near transfer (similar context) is easier than far transfer (different domain). Building abstract principles, not just specific examples, is what enables far transfer. Ask 'what general rule does this illustrate?'",tags:["advanced","mechanism"],difficulty:3},
      {id:"l-12",order:12,title:"Building the Learning Habit",body:"Consistency beats intensity. Thirty minutes of daily deliberate practice outperforms a weekend cram. The key variable is not total hours but regularity of retrieval and review.",context:"Habits reduce the decision cost of starting. Anchor study sessions to existing routines — after coffee, before dinner — and keep the session short enough to start without resistance. The session length expands naturally.",tags:["habit","foundational"],difficulty:1},
    ]
  }]
};

export const COMMUNITY_DECKS=[
  {
    id:"community-stoicism",title:"Stoic Philosophy",
    description:"Ancient wisdom for modern life — control, resilience, and living well.",
    type:"topic",path:[],
    cards:[
      {id:"cs-1",order:1,title:"What Is Stoicism?",body:"Stoicism is a philosophy founded in ancient Greece that teaches we cannot control external events, only our responses to them. The goal is to live according to reason and virtue, regardless of circumstance.",context:"Stoicism was founded by Zeno of Citium around 300 BC and later developed by Epictetus, Marcus Aurelius, and Seneca. It wasn't originally an academic philosophy — it was a practical guide for living.",tags:["foundational"],difficulty:1},
      {id:"cs-2",order:2,title:"The Dichotomy of Control",body:"Everything falls into two categories: what is 'up to us' (our judgments, desires, actions) and what is not (our body, reputation, wealth, others' opinions). Wisdom begins with knowing the difference.",context:"Epictetus — a former slave — made this the foundation of his teaching. His point: misery comes from wanting control over things you don't have. Freedom comes from focusing only on what you do have.",tags:["foundational","mechanism"],difficulty:1},
      {id:"cs-3",order:3,title:"Negative Visualisation",body:"Periodically imagine losing the things you value — your health, relationships, possessions. This isn't pessimism; it's a technique for appreciating what you have before it's gone.",context:"The Stoics called this premeditatio malorum — premeditation of evils. Modern psychology confirms it: people who contemplate loss experience significantly more gratitude than those who simply list blessings.",tags:["technique"],difficulty:1},
      {id:"cs-4",order:4,title:"Amor Fati — Love of Fate",body:"Amor fati means 'love of fate'. Not merely accepting what happens, but actively willing it — treating every obstacle as something to be desired, not merely endured.",context:"Marcus Aurelius: 'The impediment to action advances action. What stands in the way becomes the way.' This reframe doesn't change events; it changes what those events mean to you, which changes everything.",tags:["mindset","mechanism"],difficulty:2},
      {id:"cs-5",order:5,title:"Memento Mori",body:"Memento mori — 'remember you will die' — is a Stoic practice of regularly contemplating mortality. Not morbidly, but as a device for prioritisation and presence.",context:"Roman generals returning from victory were followed by a slave whispering 'memento mori' to prevent arrogance. Confronting death clarifies what actually matters. Many people report that awareness of mortality focuses their attention and reduces trivial anxiety.",tags:["technique","mindset"],difficulty:2},
      {id:"cs-6",order:6,title:"The Four Virtues",body:"The Stoics held that virtue is the only true good. The four cardinal virtues are: wisdom (knowing what is good), courage (acting rightly under adversity), justice (treating others fairly), and temperance (self-discipline).",context:"Crucially, the Stoics believed virtue is sufficient for happiness — external goods like wealth and health are 'preferred indifferents', nice to have but not necessary. This is a radical claim that most people find either liberating or frustrating.",tags:["foundational","values"],difficulty:2},
      {id:"cs-7",order:7,title:"The View from Above",body:"Imagine looking down at your life from a great height — your city, your country, the planet. Your problems shrink to their actual size. This perspective exercise dissolves petty grievances instantly.",context:"Marcus Aurelius used this frequently in Meditations. Modern variations include the 'overview effect' reported by astronauts who say seeing Earth from space permanently changed their sense of proportion. The technique works even as a brief mental exercise.",tags:["technique","advanced"],difficulty:3},
    ]
  },
  {
    id:"community-finance",title:"Financial Literacy 101",
    description:"Core money concepts every adult should understand — no jargon.",
    type:"topic",path:[],
    cards:[
      {id:"cf-1",order:1,title:"Income vs Wealth",body:"Income is money flowing in each period. Wealth is accumulated assets minus liabilities. High income doesn't create wealth; the gap between what you earn and what you spend does.",context:"Many high earners remain financially fragile because they increase spending with every pay rise. Wealth is built by repeatedly choosing not to spend a portion of income — regardless of the amount.",tags:["foundational"],difficulty:1},
      {id:"cf-2",order:2,title:"Compound Interest",body:"Compound interest is interest earned on interest. 10,000 growing at 10% per year becomes 25,937 in 10 years — not 20,000 — because each year's gains are added to the base.",context:"Einstein allegedly called compound interest the eighth wonder of the world. The key insight is the exponential curve: returns feel slow at first and then accelerate dramatically. Starting 10 years earlier roughly doubles the end result.",tags:["mechanism","foundational"],difficulty:1},
      {id:"cf-3",order:3,title:"Assets vs Liabilities",body:"An asset puts money into your pocket. A liability takes money out. A house you live in costs you money every month — it's a liability until sold at a profit. A rental property that generates income is an asset.",context:"Robert Kiyosaki's framing from Rich Dad Poor Dad is blunt but useful: rich people buy assets; others buy liabilities they think are assets. The car, the boat, the designer clothing — all liabilities. Income-generating things — assets.",tags:["foundational","mechanism"],difficulty:1},
      {id:"cf-4",order:4,title:"Inflation",body:"Inflation is the general rise in prices over time. At 6% annual inflation, money loses half its purchasing power in about 12 years. Cash sitting in a low-interest account loses real value every year.",context:"The 'Rule of 72' estimates how long it takes to halve purchasing power: divide 72 by the inflation rate. At 6%, about 12 years. This is why holding large amounts of cash long-term is a form of losing money slowly.",tags:["mechanism","foundational"],difficulty:1},
      {id:"cf-5",order:5,title:"Opportunity Cost",body:"Every financial decision has an opportunity cost — what you give up by not choosing the alternative. Buying a car for a large sum isn't just spending that money; it's also not investing that amount for 20 years.",context:"Opportunity cost is invisible, which makes it easy to ignore. But wealth-building requires making it visible. The question is never just 'can I afford this?' It's 'what am I giving up by spending this?'",tags:["concept","mechanism"],difficulty:2},
      {id:"cf-6",order:6,title:"Diversification",body:"Diversification means spreading investments across different assets so poor performance in one doesn't devastate the whole. 'Don't put all your eggs in one basket' is the oldest financial advice for a reason.",context:"Diversification reduces risk without necessarily reducing expected returns — which is why economists call it 'the only free lunch in finance'. A mix of stocks, bonds, and other assets historically produces smoother returns than any single asset.",tags:["strategy","mechanism"],difficulty:2},
      {id:"cf-7",order:7,title:"Emergency Fund",body:"An emergency fund is 3–6 months of living expenses held in liquid, accessible savings. Its purpose is to absorb shocks — job loss, medical bills, major repairs — without forced selling of investments.",context:"Most financial stress is liquidity stress, not wealth stress. People with adequate emergency funds make calmer decisions. Without one, a single unexpected expense can trigger a spiral: credit card debt → high interest → harder to save → no fund → more vulnerability.",tags:["foundational","strategy"],difficulty:1},
      {id:"cf-8",order:8,title:"Time Value of Money",body:"A unit of money today is worth more than the same unit tomorrow because today's money can be invested and grow. This principle underpins all of finance — loans, investments, valuations, retirement planning.",context:"The time value of money explains why paying off high-interest debt early is so powerful, why starting to invest young matters so much, and why buying on credit costs more than paying cash. Every delayed decision has a calculable cost.",tags:["foundational","mechanism"],difficulty:2},
    ]
  },
  {
    id:"community-publicspeaking",title:"The Art of Public Speaking",
    description:"Speak clearly, connect with any audience, and handle the nerves.",
    type:"topic",path:[],
    cards:[
      {id:"cp-1",order:1,title:"Why It Matters More Than You Think",body:"Public speaking is consistently ranked as one of the top skills for career advancement and leadership. The ability to communicate ideas clearly in front of others amplifies everything else you know how to do.",context:"Warren Buffett has said that the best investment he ever made was a Dale Carnegie public speaking course at age 20. Communication is a force multiplier — it makes your expertise visible and actionable to others.",tags:["foundational"],difficulty:1},
      {id:"cp-2",order:2,title:"Anxiety Is Normal — Use It",body:"Speaking anxiety affects approximately 75% of people. The physical symptoms — racing heart, dry mouth, shaky hands — are identical to excitement. Reframing 'I'm nervous' as 'I'm excited' measurably improves performance.",context:"Research by Alison Wood Brooks at Harvard found that telling yourself 'I am excited' before a high-stakes situation outperforms 'I am calm' on objective performance measures. Anxiety can't be turned off; it can be redirected.",tags:["mindset","foundational"],difficulty:1},
      {id:"cp-3",order:3,title:"Know Your Audience",body:"Every speech is a gift to the audience, not a performance for yourself. Before preparing content, ask: what does this audience already know? What do they need? What will make them care?",context:"The most common mistake in presentations is failing to translate expertise into audience-relevant terms. An engineer presenting to executives needs a different structure than one presenting to peers. Audience analysis is the first step, not the last.",tags:["foundational","technique"],difficulty:1},
      {id:"cp-4",order:4,title:"The Rule of Three",body:"Information delivered in threes is significantly more memorable than any other grouping. 'Life, liberty, and the pursuit of happiness.' Three points create rhythm, completeness, and retention.",context:"The rule of three works because the human brain naturally groups information in patterns. Three is the minimum for pattern recognition and the maximum that can be held comfortably without notes. Most great speeches have three main ideas.",tags:["technique","mechanism"],difficulty:1},
      {id:"cp-5",order:5,title:"The Power of the Pause",body:"Strategic silence is one of the most underused tools in speaking. Pausing before a key point creates anticipation. Pausing after creates space for the idea to land. Most speakers fill silence with 'um' and 'uh' out of discomfort.",context:"Research shows audiences perceive speakers who pause as more competent and confident, not less. The pause feels long only to the speaker — the audience experiences it as gravitas. Practice by rehearsing with a deliberate one-second gap after every sentence.",tags:["technique"],difficulty:2},
      {id:"cp-6",order:6,title:"Eye Contact That Connects",body:"Effective eye contact means holding a genuine connection with one person for a complete thought (3–5 seconds) before moving to another. Rapid scanning or staring at slides signals disengagement and reduces trust.",context:"One-person-per-thought eye contact transforms a speech into a series of individual conversations. The person you're looking at feels personally addressed. The audience around them feel it too — it creates a sense of intimacy even in large rooms.",tags:["technique"],difficulty:2},
      {id:"cp-7",order:7,title:"Handling Questions",body:"Repeat or paraphrase every question before answering — it buys thinking time, ensures accuracy, and ensures the whole audience heard it. Answer the question asked, not the question you wish they'd asked.",context:"The phrase 'That's a great question' is now widely recognised as a stalling tactic. Instead: repeat the question, take a brief pause, then answer directly. If you don't know, say so — it builds more credibility than a vague answer.",tags:["technique","advanced"],difficulty:3},
    ]
  },
];
